### PR TITLE
Compatibility with rocket v5.0

### PR DESCRIPTION
**Pull request by kloneets**
Since rocket v5.0 stable is here:
- updated rocket version in Cargo.toml
- made changes, so, lib is compatible with http::cokkie v0.18.0

### CODE REVIEW

**Comment by justinacolmena** [comment]
Where is the new crate for this commit?

https://crates.io/crates/rocket-session-store/versions

**Comment by kloneets** [comment]
I suppose, this is up to @Aurora2500. If you cannot wait, for now you can use it like this in `Cargo.toml` 
```toml
# ...
rocket-session-store = { version = "0.2.1", features = ["redis"], git="https://github.com/Aurora2500/rocket-session-store.git" }
# ...
```

**Comment by vtaits** [comment]
any progress here?

**Comment by justinacolmena** [comment]
Not really. I was very curious and excited to learn Rust as a programming language but stateside law operatives at the Alaska Department of Law and University of Alaska Fairbanks have strong vested competing proprietary software interests and are apparently violently opposed to any and all free & open source software projects. My truck, laptop computers etc. were all confiscated by City Hall in Anchorage a year ago, another cop mugged me on the street & the city attorney was fired after his henchman pulled a gun on me when I complained, but I still haven't got restitution from the city for my property which was wrongfully appropriated by those crooks. No Trespassing at places of business that appear open to the public, and pimps & human traffickers are in charge of all the hotels & apartments. Anybody else have it any easier? I think most of this Rust stuff is pretty solid so far, given the sort of thieves trying to crack it. Too many gold thieves have taken up residence around the Fort Knox Gold Mine.

**Pull request merged**
